- name: installing docker-compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}'
    dest: '/usr/local/bin/docker-compose'
    mode: 0755

- name: granting all permissions to user through docker-compose io
  file: 
    path: /usr/local/bin/docker-compose
    mode: +x
  become: yes

- name: granting all permissions to user through docker-compose io
  shell: chown {{ username }}:{{ username }} /var/run/docker.sock
  become: yes